package(
  default_visibility = ["//visibility:public"],
)

filegroup(
  name = "demo_projects",
  srcs = [
    "amida.z2music",
    "rog.z2music",
    "solstice.z2music",
    "benthic_king.z2music",
  ],
)
