cc_binary(
    name = "solstice",
    srcs = ["solstice.cc"],
    deps = ["//:music"],
)

cc_binary(
    name = "rog",
    srcs = ["rog.cc"],
    deps = ["//:music"],
)

cc_binary(
    name = "undersea",
    srcs = ["undersea.cc"],
    deps = ["//:music"],
)

cc_binary(
    name = "amida",
    srcs = ["amida.cc"],
    deps = ["//:music"],
)
